[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM30
monitor_port = COM30
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    SparkFun MAX3010x Pulse and Proximity Sensor Library