"""
convert_to_tflite.py

Converts the trained Keras model to a quantized (int8) TFLite Micro model
and emits it as a C header (model_data.h) ready to drop into
firmware/model/, replacing the placeholder there.

Usage:
  python convert_to_tflite.py --model ./model/model.h5 \
      --out ../firmware/model/model_data.h \
      --calib_data ./data/features.csv
"""
import argparse
import os
import numpy as np
import pandas as pd
import tensorflow as tf

FEATURE_COLS = [
    "PI_finger", "PI_toe", "PI_ratio", "PTT_ft",
    "AI_finger", "AI_toe", "HRV_rmssd", "dicrotic_ratio",
]


def representative_dataset_gen(calib_data_path, scaler_mean, scaler_scale):
    df = pd.read_csv(calib_data_path, encoding="utf-8")
    X = df[FEATURE_COLS].to_numpy(dtype=np.float32)
    X_scaled = (X - scaler_mean) / scaler_scale

    def gen():
        for i in range(min(200, len(X_scaled))):
            yield [X_scaled[i:i + 1].astype(np.float32)]
    return gen


def write_c_array(tflite_bytes, out_path):
    var_name = "g_pvd_model_data"
    lines = [
        "#pragma once",
        "#include <cstdint>",
        "",
        "// Auto-generated by ml_pipeline/convert_to_tflite.py. Do not hand-edit.",
        f"alignas(8) const unsigned char {var_name}[] = {{",
    ]
    hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
    for i in range(0, len(hex_bytes), 12):
        lines.append("    " + ", ".join(hex_bytes[i:i + 12]) + ",")
    lines.append("};")
    lines.append(f"const int {var_name}_len = {len(tflite_bytes)};")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(tflite_bytes)} bytes as C array to {out_path}")


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=os.path.join(script_dir, "model", "saved_model"))
    parser.add_argument("--out", default=os.path.abspath(os.path.join(script_dir, "..", "firmware", "model", "model_data.h")))
    parser.add_argument("--calib_data", default=os.path.join(script_dir, "data", "features.csv"))
    parser.add_argument("--scaler_dir", default=os.path.join(script_dir, "model"))
    args = parser.parse_args()

    scaler_mean = np.load(f"{args.scaler_dir}/scaler_mean.npy")
    scaler_scale = np.load(f"{args.scaler_dir}/scaler_scale.npy")

    converter = tf.lite.TFLiteConverter.from_saved_model(args.model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen(
        args.calib_data, scaler_mean, scaler_scale)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.float32   # keep float I/O; only
    converter.inference_output_type = tf.float32  # weights are int8-quantized

    tflite_model = converter.convert()
    print(f"Quantized model size: {len(tflite_model) / 1024:.1f} KB")

    write_c_array(tflite_model, args.out)

    print("\nReminder: the firmware feature extraction must feed the SAME "
          "standardized (mean/scale) inputs the model was trained on. "
          "Either bake scaler_mean.npy/scaler_scale.npy into "
          "feature_extraction.cpp as constants, or add a normalization "
          "step in tinyml_inference.cpp before calling interpreter->Invoke().")


if __name__ == "__main__":
    main()
